### ISSUE TITLE
\songti加粗

### ISSUE THREAD

**Issue by GreenTeacom** [zhangning737/njustThesisMaster#1]
同学你好：
.cls文件中，下述代码中\bf无法加粗宋体，另外标题都有这个\bf无法加粗宋体的问题
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% 2. CHN kewords
\newcommand\keywords[1]{%
  \vspace{2ex}\noindent{\bf\songti\zihao{4} \NJUST@label@keywords} #1}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
请问如何解决？

**Comment by zhangning737** [comment]
@GreenTeacom 你好，目前MacTex 2019测试无此问题，请问是用的哪个tex发行包编译的啊

**Comment by zhangning737** [comment]
> 同学你好：
> .cls文件中，下述代码中\bf无法加粗宋体，另外标题都有这个\bf无法加粗宋体的问题
> %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
> %% 2. CHN kewords
> \newcommand\keywords[1]{%
> \vspace{2ex}\noindent{\bf\songti\zihao{4} \NJUST@label@keywords} #1}
> %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
> 请问如何解决？

@GreenTeacom 你好，目前MacTex 2019测试无此问题，请问是用的哪个tex发行包编译的啊

**Comment by GreenTeacom** [comment]
texlive2019+Texstudio

**Comment by zhangning737** [comment]
> texlive2019+Texstudio

是否有warning 或者error 信息啊

**Comment by GreenTeacom** [comment]
texlive2019+Texstudio能够正常编译，没有error，编译的警告及典型PDF显示如下：（另外“目录”中没有“参考文献”）（可以留个邮箱吗？）
![1](https://user-images.githubusercontent.com/24284789/72890420-ccbd7a80-3d4c-11ea-98b0-27822955309a.png)
![2](https://user-images.githubusercontent.com/24284789/72890422-cd561100-3d4c-11ea-8bd2-51cadee8bddb.png)
![3](https://user-images.githubusercontent.com/24284789/72890428-ce873e00-3d4c-11ea-9bb0-c7f44483ed5f.png)
![4](https://user-images.githubusercontent.com/24284789/72890430-cf1fd480-3d4c-11ea-948c-07c7a37c43b8.png)
![5](https://user-images.githubusercontent.com/24284789/72891081-5de12100-3d4e-11ea-9aca-74b310b09732.png)
![6](https://user-images.githubusercontent.com/24284789/72891082-5e79b780-3d4e-11ea-8a7c-8011d90e1f9e.png)

**Comment by zhangning737** [comment]
@GreenTeacom 字体加粗的问题，mac和linux上没有，win上确实存在，应该是字体兼容性的问题，后续解决。bib不在目录里的问题已解决，85661758@qq.com

**Comment by zhangning737** [comment]
@GreenTeacom 字体问题参见[知乎](https://www.zhihu.com/question/58456658/answer/157120688)

win下需要配置字体，安装可以加粗的字体或者伪加粗。

已在说明里更改 pdflatex 对windows字体支持比较好
